name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: 17

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
