name: Release

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --all --tags

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Run distribution build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distZip

      - name: Get release notes
        id: release-notes
        run: |
          echo "notes=$(git tag -l --format='%(contents:body)' ${{ github.ref_name }})" >> $GITHUB_OUTPUT
          echo $(git tag -l --format='%(contents:subject)%0a%(contents:body)' ${{ github.ref_name }})

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{  github.ref_name }}
          body: |
            ### What's changed?
            ${{ steps.release-notes.outputs.notes }}
          files: build/distributions/*.zip