name: Release

on:
  push:
    tags:
      - '*'
      
env:
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "${{ env.JAVA_VERSION }}"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run distribution build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distZip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{  github.ref_name }}
          body: "### What's changed?\n - ..."
          files: build/distributions/*.zip